enableConstraintsChecks: true

supportedArchitectures:
  os: ["darwin"]
  cpu: ["x64", "arm64"]

enableHardenedMode: true

enableInlineHunks: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.13.0.cjs
